/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Personas.Usuario;
import javax.swing.JOptionPane;
/*
Este form se encarga de hacer el enlace de inicio de sesion con la base de datos

*/
/**
 *
 * @author jose miguel
 */
public class Menu_InicioSesion extends javax.swing.JFrame {

    /**
     * Creates new form menu_inicio_session
     */
    public Menu_InicioSesion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JT_User = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JT_Contra = new javax.swing.JTextField();
        JB_Iniciar = new javax.swing.JButton();
        JB_NewUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre Usuario");

        JT_User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT_UserActionPerformed(evt);
            }
        });

        jLabel2.setText("Contraseña ");

        JT_Contra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT_ContraActionPerformed(evt);
            }
        });

        JB_Iniciar.setText("Iniciar sesion");
        JB_Iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_IniciarActionPerformed(evt);
            }
        });

        JB_NewUsuario.setText("Crear Nuevo Usuario");
        JB_NewUsuario.setActionCommand("JB_NewUsuario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JT_User)
                            .addComponent(JT_Contra))
                        .addGap(61, 61, 61))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JB_Iniciar, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                        .addGap(51, 51, 51)
                        .addComponent(JB_NewUsuario)
                        .addGap(41, 41, 41))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JT_User, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JT_Contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_Iniciar)
                    .addComponent(JB_NewUsuario))
                .addContainerGap(399, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_IniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_IniciarActionPerformed
        // TODO add your handling code here:
        if (JT_User.getText().length() == 0) {
            //checa si no hay nada escrito en el jText de usuario
            JOptionPane.showMessageDialog(null, "Debes ingresar un UserName");
            JT_User.requestFocus();
            System.out.println();
            return;
        }
        
        if (JT_Contra.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Debes ingresar una contraseña");
            //checa si no hay nada escrito en el jText de contraseña
            JT_Contra.requestFocus();
            System.out.println();
            return;
        }
        
        try{
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error "+e);
            System.out.println(e);
        }
    }//GEN-LAST:event_JB_IniciarActionPerformed

    private void JT_UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT_UserActionPerformed
        // TODO add your handling code here:
        this.transferFocus();
        //este metodo transfiere el "enfoque" (cursor) cuando se termina de escribir
        //y se transfiere el cursor al siguiente jText
    }//GEN-LAST:event_JT_UserActionPerformed

    private void JT_ContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT_ContraActionPerformed
        // TODO add your handling code here:
        this.transferFocus();
    }//GEN-LAST:event_JT_ContraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_InicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_Iniciar;
    private javax.swing.JButton JB_NewUsuario;
    private javax.swing.JTextField JT_Contra;
    private javax.swing.JTextField JT_User;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
