/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Personas.proveedor;
import javax.swing.JOptionPane;

/**
 *
 * @author jose miguel
 */
public class Menu_NewProveedor extends javax.swing.JPanel {

    /**
     * Creates new form Menu_NewProovedor
     */
    public Menu_NewProveedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JT_NewDireccion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JL_NewDia = new javax.swing.JList<>();
        JR_NewHombre = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        JL_NewAño = new javax.swing.JList<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JS_NewMes = new javax.swing.JScrollPane();
        JL_NewMes = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JB_NewUser = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        JT_NewNombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        JT_NewRFC = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JT_NewMail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        JT_NewTel = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        JT_NewMail1 = new javax.swing.JTextField();

        JT_NewDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT_NewDireccionActionPerformed(evt);
            }
        });

        jLabel9.setText("Crear nuevo proveedor");

        JL_NewDia.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(JL_NewDia);

        JR_NewHombre.setText("Hombre");
        JR_NewHombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JR_NewHombreActionPerformed(evt);
            }
        });

        jRadioButton2.setText("Mujer");

        JL_NewAño.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950", "1949", "1948", "1947", "1946", "1945", "1944", "1943", "1942", "1941", "1940" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(JL_NewAño);

        jLabel10.setText("Sexo");

        jLabel1.setText("Nombre");

        jLabel2.setText("Direccion");

        JL_NewMes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        JS_NewMes.setViewportView(JL_NewMes);

        jLabel3.setText("RFC");

        jLabel4.setText("Fecha nacimiento");

        JB_NewUser.setText("Crear Nuevo Usuario");
        JB_NewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_NewUserActionPerformed(evt);
            }
        });

        jLabel6.setText("Dia");

        JT_NewNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT_NewNombreActionPerformed(evt);
            }
        });

        jLabel7.setText("Mes");

        JT_NewRFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT_NewRFCActionPerformed(evt);
            }
        });

        jLabel8.setText("Año");

        jLabel5.setText("telefono");

        jLabel11.setText("correo");

        JT_NewTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT_NewTelActionPerformed(evt);
            }
        });

        jLabel12.setText("ID_Pedido");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(JB_NewUser))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JT_NewMail1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JT_NewMail, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(JT_NewNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(JT_NewRFC, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(JT_NewDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(102, 102, 102)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6))
                                    .addGap(43, 43, 43)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel7)
                                        .addComponent(JS_NewMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(32, 32, 32)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8))
                                    .addGap(45, 45, 45)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(JR_NewHombre)
                                        .addComponent(jRadioButton2)))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(207, 207, 207)
                            .addComponent(jLabel9)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(109, Short.MAX_VALUE)
                    .addComponent(JT_NewTel, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(23, 23, 23)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(jLabel4)
                .addGap(75, 75, 75)
                .addComponent(jLabel5)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(JT_NewMail1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(JT_NewMail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(JB_NewUser)
                .addGap(25, 25, 25))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(61, 61, 61)
                    .addComponent(jLabel9)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addComponent(JT_NewNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(JT_NewDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(JT_NewRFC, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(7, 7, 7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(JS_NewMes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(JR_NewHombre)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jRadioButton2)))
                    .addContainerGap(251, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(322, Short.MAX_VALUE)
                    .addComponent(JT_NewTel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(190, 190, 190)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JT_NewDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT_NewDireccionActionPerformed
        // TODO add your handling code here:
        JT_NewDireccion.transferFocus();
        //este metodo transfiere el "enfoque" (cursor) cuando se termina de escribir
        //y se transfiere el cursor al siguiente jText
    }//GEN-LAST:event_JT_NewDireccionActionPerformed

    private void JR_NewHombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JR_NewHombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JR_NewHombreActionPerformed

    private void JB_NewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_NewUserActionPerformed
        // TODO add your handling code here:
        /*
        Creacion del objeto persona "PROVEEDOR"
        */
        
        //este recorrido de ifs se asegura de no dejar campos abiertos
        
        if (JT_NewNombre.getText().length() == 0) {
            //checa si no hay nada escrito en el jText de usuario
            JOptionPane.showMessageDialog(null, "Debes ingresar un nombre");
            JT_NewNombre.requestFocus();
            return;
        }

        if (JT_NewDireccion.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Debes ingresar una direccion");
            //checa si no hay nada escrito en el jText de contraseña
            JT_NewDireccion.requestFocus();
            return;
        }

        if (JT_NewRFC.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Debes ingresar una CURP");
            JT_NewRFC.requestFocus();
        }
        
        if (JT_NewMail.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Debes ingresar un mail");
            JT_NewMail.requestFocus();
        }
        
        if (JT_NewTel.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Debes ingresar un telefono (puros numeros)");
            JT_NewRFC.requestFocus();
        }

        try{
           // (String Nombre, String Direccion, String RFC, 
           // String Correo, int Dia, int Mes, int Año, int Tel
            proveedor newProveedor = new proveedor(
                JT_NewNombre.getText(), JT_NewDireccion.getText(), JT_NewRFC.getText(), JT_NewMail.getText(),
                JL_NewDia.getSelectedIndex(), JL_NewMes.getSelectedIndex(), JL_NewAño.getSelectedIndex(), JT_NewTel.getText()
            );//termina constructor de Usuario
            System.out.println(newProveedor.calcEdad());
            //calculo rapido de la edad, segun la fecha establecida por el usuario
        }catch(Exception e){

        }
    }//GEN-LAST:event_JB_NewUserActionPerformed

    private void JT_NewNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT_NewNombreActionPerformed
        // TODO add your handling code here:
        JT_NewNombre.transferFocus();
        //este metodo transfiere el "enfoque" (cursor) cuando se termina de escribir
        //y se transfiere el cursor al siguiente jText
    }//GEN-LAST:event_JT_NewNombreActionPerformed

    private void JT_NewRFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT_NewRFCActionPerformed
        // TODO add your handling code here:
        JT_NewRFC.transferFocus();
        //este metodo transfiere el "enfoque" (cursor) cuando se termina de escribir
        //y se transfiere el cursor al siguiente jText
    }//GEN-LAST:event_JT_NewRFCActionPerformed

    private void JT_NewTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT_NewTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT_NewTelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_NewUser;
    private javax.swing.JList<String> JL_NewAño;
    private javax.swing.JList<String> JL_NewDia;
    private javax.swing.JList<String> JL_NewMes;
    private javax.swing.JRadioButton JR_NewHombre;
    private javax.swing.JScrollPane JS_NewMes;
    private javax.swing.JTextField JT_NewDireccion;
    private javax.swing.JTextField JT_NewMail;
    private javax.swing.JTextField JT_NewMail1;
    private javax.swing.JTextField JT_NewNombre;
    private javax.swing.JTextField JT_NewRFC;
    private javax.swing.JTextField JT_NewTel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
